import type { LedgerRepository } from './ledger.repository.js';
import { NotFoundError } from '../../shared/errors.js';
import type { AutoLedgerParams, SourceModule, ListParams } from './ledger.types.js';
import type { DashboardService } from '../dashboard/dashboard.service.js';
import { paginate } from '../../shared/pagination.js';

const ALLOWED_SORT = ['transaction_date', 'amount', 'description', 'status'];

export class LedgerService {
  constructor(
    private readonly repo: LedgerRepository,
    private readonly dashboard: DashboardService,
  ) {}

  /**
   * Insert a read-only ledger entry generated by a domain module.
   * Does NOT call upsertSnapshot — caller is responsible (already called in domain service).
   */
  autoEntry(params: AutoLedgerParams): void {
    this.repo.insertAutoEntry(params);
  }

  /**
   * When a source record is deleted, soft-delete its auto ledger entries.
   */
  softDeleteAutoEntries(source_module: SourceModule, source_id: number): void {
    this.repo.softDeleteAutoEntries(source_module, source_id);
  }

  listEntries(params: ListParams) {
    const {
      assetClass, entryType, dateFrom, dateTo, status, search,
      includeVoided = false,
      sort = 'transaction_date', sortDir = 'desc', page = 1,
    } = params;

    const safeSort = ALLOWED_SORT.includes(sort) ? `le.${sort}` : 'le.transaction_date';
    const safeDir = sortDir.toLowerCase() === 'asc' ? 'ASC' : 'DESC';

    const conditions: string[] = ['le.deleted_at IS NULL'];
    const bindings: (string | number)[] = [];

    // Terminal statuses ('voided', 'reversed') require seeing entries that would
    // otherwise be hidden. When explicitly filtering by one of these, skip the
    // voided_at IS NULL guard so the filter actually returns results.
    const isTerminalStatusFilter = status === 'voided' || status === 'reversed';

    if (!includeVoided && !isTerminalStatusFilter) {
      conditions.push('le.voided_at IS NULL');
    }

    if (assetClass) {
      conditions.push('ac.code = ?');
      bindings.push(assetClass);
    }
    if (entryType) {
      conditions.push('le.entry_type = ?');
      bindings.push(entryType);
    }
    if (dateFrom) {
      conditions.push('le.transaction_date >= ?');
      bindings.push(dateFrom);
    }
    if (dateTo) {
      conditions.push('le.transaction_date <= ?');
      bindings.push(dateTo + 'T23:59:59.999Z');
    }
    if (status) {
      conditions.push('le.status = ?');
      bindings.push(status);
    }
    if (search && search.trim()) {
      conditions.push('(le.description LIKE ? OR le.notes LIKE ?)');
      const term = `%${search.trim()}%`;
      bindings.push(term, term);
    }

    const total_count = this.repo.countEntries(conditions, bindings);
    const rows = this.repo.listEntries(conditions, bindings, safeSort, safeDir, page);

    return paginate(rows, total_count, page);
  }

  getEntryById(id: number) {
    const row = this.repo.findById(id);
    if (!row) throw new NotFoundError('Ledger entry', id);
    return row;
  }

  createEntry(data: {
    asset_class_id: number; institution_id?: number; entry_type: string;
    description: string; amount: string; status?: string; transaction_date: string; notes?: string;
  }) {
    const id = this.repo.insertEntry(data);
    this.dashboard.upsertSnapshot();
    return this.getEntryById(id);
  }

  updateEntry(id: number, data: Partial<{
    asset_class_id: number; institution_id: number; entry_type: string;
    description: string; amount: string; status: string; transaction_date: string;
    notes: string; edit_reason: string;
  }> & { edit_reason?: string }) {
    this.getEntryById(id);

    // Snapshot before every edit so the audit trail is complete
    this.repo.snapshotVersion(id, data.edit_reason ?? null);

    const sets: string[] = ["updated_at = datetime('now')"];
    const vals: (string | number | null)[] = [];

    if (data.asset_class_id !== undefined) { sets.push('asset_class_id = ?'); vals.push(data.asset_class_id); }
    if (data.institution_id !== undefined) { sets.push('institution_id = ?'); vals.push(data.institution_id); }
    if (data.entry_type !== undefined) { sets.push('entry_type = ?'); vals.push(data.entry_type); }
    if (data.description !== undefined) { sets.push('description = ?'); vals.push(data.description); }
    if (data.amount !== undefined) { sets.push('amount = ?'); vals.push(data.amount); }
    if (data.status !== undefined) { sets.push('status = ?'); vals.push(data.status); }
    if (data.transaction_date !== undefined) { sets.push('transaction_date = ?'); vals.push(data.transaction_date); }
    if (data.notes !== undefined) { sets.push('notes = ?'); vals.push(data.notes); }

    this.repo.updateEntry(id, sets, vals);
    this.dashboard.upsertSnapshot();
    return this.getEntryById(id);
  }

  /**
   * Reverse an entry: creates a mirror row with negated amount (the reversal),
   * marks the original as status='reversed', and returns the reversal entry.
   *
   * This follows the double-entry bookkeeping pattern used by QuickBooks/Xero:
   *   original  -300,000,000  [reversed]
   *   reversal  +300,000,000  [completed]  ← returned here
   * After this, the caller should create a new corrected entry.
   */
  reverseEntry(id: number, reason: string) {
    const original = this.getEntryById(id);
    const status = (original as Record<string, unknown>).status as string;
    if (status === 'voided') throw new Error('Voided entries cannot be reversed. They are already cancelled.');
    if (status === 'reversed') throw new Error('Entry has already been reversed.');
    if ((original as Record<string, unknown>).is_auto === 1) {
      throw new Error('Auto-generated entries cannot be reversed directly. Correct the source record instead.');
    }
    const reversalId = this.repo.insertReversalEntry(original as Record<string, unknown>, reason);
    this.repo.markAsReversed(id);
    this.dashboard.upsertSnapshot();
    return this.getEntryById(reversalId);
  }

  getEntryVersions(id: number) {
    this.getEntryById(id);
    return this.repo.getVersions(id);
  }

  /**
   * Void an entry with a mandatory reason.
   * This is the correct accounting practice — never delete, always void.
   * Voided entries are excluded from balance calculations but preserved
   * for audit trail and reconciliation purposes.
   */
  voidEntry(id: number, reason: string) {
    const entry = this.getEntryById(id);
    // Auto-generated entries cannot be voided directly —
    // they must be corrected at the source module
    if ((entry as Record<string, unknown>).is_auto === 1) {
      throw new Error('Auto-generated entries cannot be voided. Please correct the source record.');
    }
    if ((entry as Record<string, unknown>).voided_at) {
      throw new Error('Entry is already voided.');
    }
    this.repo.voidEntry(id, reason);
    this.dashboard.upsertSnapshot();
    return this.getEntryById(id);
  }

  softDeleteEntry(id: number) {
    this.getEntryById(id);
    this.repo.softDeleteEntry(id);
    this.dashboard.upsertSnapshot();
    return this.repo.findDeletedAt(id);
  }

  /**
   * Lightweight status-only update — avoids full PUT payload for a single field change.
   * Used by inline status click in the UI.
   */
  updateStatus(id: number, status: string) {
    this.getEntryById(id);
    this.repo.updateEntry(id, ["status = ?", "updated_at = datetime('now')"], [status]);
    this.dashboard.upsertSnapshot();
    return this.getEntryById(id);
  }

  /**
   * Bulk status update — update up to 500 entries in a single transaction.
   * Only updates manual entries (is_auto = 0) to protect auto-generated records.
   */
  bulkUpdateStatus(ids: number[], status: string) {
    const updated = this.repo.bulkUpdateStatus(ids, status);
    this.dashboard.upsertSnapshot();
    return { updated_count: updated, status };
  }
}
