import type { LedgerRepository } from './ledger.repository.js';
import { NotFoundError } from '../../shared/errors.js';
import type { AutoLedgerParams, SourceModule, ListParams } from './ledger.types.js';
import type { DashboardService } from '../dashboard/dashboard.service.js';

const ALLOWED_SORT = ['transaction_date', 'amount', 'description', 'status'];

export class LedgerService {
  constructor(
    private readonly repo: LedgerRepository,
    private readonly dashboard: DashboardService,
  ) {}

  /**
   * Insert a read-only ledger entry generated by a domain module.
   * Does NOT call upsertSnapshot — caller is responsible (already called in domain service).
   */
  autoEntry(params: AutoLedgerParams): void {
    this.repo.insertAutoEntry(params);
  }

  /**
   * When a source record is deleted, soft-delete its auto ledger entries.
   */
  softDeleteAutoEntries(source_module: SourceModule, source_id: number): void {
    this.repo.softDeleteAutoEntries(source_module, source_id);
  }

  listEntries(params: ListParams) {
    const {
      assetClass, entryType, dateFrom, dateTo, status,
      sort = 'transaction_date', sortDir = 'desc', page = 1,
    } = params;

    const safeSort = ALLOWED_SORT.includes(sort) ? `le.${sort}` : 'le.transaction_date';
    const safeDir = sortDir.toLowerCase() === 'asc' ? 'ASC' : 'DESC';

    const conditions: string[] = ['le.deleted_at IS NULL'];
    const bindings: (string | number)[] = [];

    if (assetClass) {
      conditions.push('ac.code = ?');
      bindings.push(assetClass);
    }
    if (entryType) {
      conditions.push('le.entry_type = ?');
      bindings.push(entryType);
    }
    if (dateFrom) {
      conditions.push('le.transaction_date >= ?');
      bindings.push(dateFrom);
    }
    if (dateTo) {
      conditions.push('le.transaction_date <= ?');
      bindings.push(dateTo + 'T23:59:59.999Z');
    }
    if (status) {
      conditions.push('le.status = ?');
      bindings.push(status);
    }

    const total_count = this.repo.countEntries(conditions, bindings);
    const rows = this.repo.listEntries(conditions, bindings, safeSort, safeDir, page);

    return { rows, total_count, current_page: page };
  }

  getEntryById(id: number) {
    const row = this.repo.findById(id);
    if (!row) throw new NotFoundError('Ledger entry', id);
    return row;
  }

  createEntry(data: {
    asset_class_id: number; institution_id?: number; entry_type: string;
    description: string; amount: string; status?: string; transaction_date: string; notes?: string;
  }) {
    const id = this.repo.insertEntry(data);
    this.dashboard.upsertSnapshot();
    return this.getEntryById(id);
  }

  updateEntry(id: number, data: Partial<{
    asset_class_id: number; institution_id: number; entry_type: string;
    description: string; amount: string; status: string; transaction_date: string; notes: string;
  }>) {
    this.getEntryById(id);

    const sets: string[] = ["updated_at = datetime('now')"];
    const vals: (string | number | null)[] = [];

    if (data.asset_class_id !== undefined) { sets.push('asset_class_id = ?'); vals.push(data.asset_class_id); }
    if (data.institution_id !== undefined) { sets.push('institution_id = ?'); vals.push(data.institution_id); }
    if (data.entry_type !== undefined) { sets.push('entry_type = ?'); vals.push(data.entry_type); }
    if (data.description !== undefined) { sets.push('description = ?'); vals.push(data.description); }
    if (data.amount !== undefined) { sets.push('amount = ?'); vals.push(data.amount); }
    if (data.status !== undefined) { sets.push('status = ?'); vals.push(data.status); }
    if (data.transaction_date !== undefined) { sets.push('transaction_date = ?'); vals.push(data.transaction_date); }
    if (data.notes !== undefined) { sets.push('notes = ?'); vals.push(data.notes); }

    this.repo.updateEntry(id, sets, vals);
    this.dashboard.upsertSnapshot();
    return this.getEntryById(id);
  }

  softDeleteEntry(id: number) {
    this.getEntryById(id);
    this.repo.softDeleteEntry(id);
    this.dashboard.upsertSnapshot();
    return this.repo.findDeletedAt(id);
  }
}
